### ISSUE TITLE
cursor: pointer on add button

### ISSUE THREAD

**Issue by jenstornell** [medienbaecker/kirby-images#16]
A very minor thing, but the structure field has `cursor: pointer;` on the add button. Your add button looks the same, so I think that you should add it to your field as well?

```css
.structure-add-button {
  cursor: pointer;
}
```
