### ISSUE TITLE
plus button not working within kirby builder

### ISSUE THREAD

**Issue by bnomei** [medienbaecker/kirby-images#41]
i know this is a edge case. but if using this field within [kirby builder](https://github.com/TimOetting/kirby-builder) the plus button is not working. the field called `text` is selected. 
but drag'n'drop and sorting work fine.

**Comment by bnomei** [comment]
nevermind. i should not have used `text` as id for the kirby builder field for your plugin again. all works as expected now.

**Comment by medienbaecker** [comment]
So you called the builder field `text` and also called the images field `text`? Maybe I can still fix this edge case.

**Comment by bnomei** [comment]
actually i am using `extend` keyword to put blocks in separate files but flatted it would look something like this.

**mypage.yml blueprint**
```yaml
...
fields:
  text: # this should stay
    type: textarea
    label: Main Text
  builder: # kirby builder
    type: builder
    label: Blocks
    fieldsets:
      textblock:
      snippet: blocks/text
        fields:
          text: # this was my mistake. should not be named text as well
             type: textarea
             label: Block Text
```
